import { baseConfig } from '@ceproject/config/eslint/base';

export default [
  // Generated by `prisma generate`; not committed.
  { ignores: ['src/generated/**'] },
  ...baseConfig({ tsconfigRootDir: import.meta.dirname }),
];
